In [1]:
5+5

10

In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [ ]:
input_q = inputs[1]
input_q

tensor([0.5500, 0.8700, 0.6600])

In [4]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [3]:
torch.dot(input_1 , input_q)

NameError: name 'input_1' is not defined

In [4]:
scores = torch.Tensor( inputs.shape[0])

In [5]:
scores[1] = 50
scores

tensor([ 0., 50.,  0.,  0.,  0.,  0.])

In [6]:
for  id,i in enumerate( inputs):
    # print(torch.dot(i , input_q))
    
    scores[id] = torch.dot(i , input_q)
    
    

NameError: name 'input_q' is not defined

In [7]:
scores

tensor([ 0., 50.,  0.,  0.,  0.,  0.])

In [8]:
scores / scores.sum()

tensor([0., 1., 0., 0., 0., 0.])

In [9]:
att_weights_2 =  torch.softmax(scores , dim=0)

In [10]:
contrxt_v_2 = torch.zeros(inputs.shape[1])
contrxt_v_2

tensor([0., 0., 0.])

In [11]:
att_weights_2[0] * inputs[0]

tensor([8.2936e-23, 2.8931e-23, 1.7166e-22])

In [12]:
for  id,i in enumerate( inputs):
    # print(torch.dot(i , input_q))
    
    contrxt_v_2 += att_weights_2[id] * i 
    
    

In [13]:
contrxt_v_2

tensor([0.5500, 0.8700, 0.6600])

In [14]:
att_scores = torch.empty(6 , 6)

In [15]:
for  i ,x_i in enumerate( inputs):
    # print(torch.dot(i , input_q))
    for j , x_j in enumerate(inputs):
        att_scores[i , j]= torch.dot( x_i , x_j)
    
    

In [16]:
att_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [17]:
inputs @ inputs.T

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [18]:
att_weights = torch.softmax(att_scores , dim=1)

In [19]:
att_weights.sum(dim=-1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

# with weights

In [13]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [14]:
inputs.shape

torch.Size([6, 3])

In [15]:
torch.manual_seed(123)

W_query = torch.nn.Parameter( torch.rand(d_in, d_out))
W_key = torch.nn.Parameter( torch.rand(d_in, d_out))
W_value = torch.nn.Parameter( torch.rand(d_in, d_out))


In [16]:
query_2 = x_2 @ W_query

query_2

tensor([0.4306, 1.4551], grad_fn=<SqueezeBackward4>)

In [7]:
x_2

tensor([0.5500, 0.8700, 0.6600])

In [54]:
keys = inputs @ W_key
values = inputs @ W_value


keys

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]], grad_fn=<MmBackward0>)

In [30]:
0.4306 * 0.3669 +  1.4551 * 0.7646

1.2705566

In [29]:
keys.T

tensor([[0.3669, 0.4433, 0.4361, 0.2408, 0.1827, 0.3275],
        [0.7646, 1.1419, 1.1156, 0.6706, 0.3292, 0.9642]],
       grad_fn=<PermuteBackward0>)

In [31]:
attention_scores =  query_2 @ keys.T

In [43]:
keys.shape[1]

2

In [47]:
d_k = keys.shape[1]

attention_weights = torch.softmax(attention_scores / d_k ** 0.5 , dim = -1 )
attention_weights

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
       grad_fn=<SoftmaxBackward0>)

In [55]:
values

tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]], grad_fn=<MmBackward0>)

In [59]:
context_vector_2  =  attention_weights @ values
context_vector_2

tensor([0.3061, 0.8210], grad_fn=<SqueezeBackward4>)

# self attention class

In [89]:
import torch.nn as nn 

class SelfAttention_V1(nn.Module):
    
    def __init__(self , d_in , d_out , qkv_bias = False):
        super().__init__()
        
        self.W_query = torch.nn.Linear( d_in, d_out , bias = qkv_bias)
        self.W_key = torch.nn.Linear(d_in, d_out , bias = qkv_bias)
        self.W_value = torch.nn.Linear( d_in, d_out , bias = qkv_bias)
        
    def forward(self , x):
        
        query =  self.W_query(x)
        keys =  self.W_key(x)
        values =  self.W_value(x)


        att_scores = (query @ keys.T) 
        
        d_k = keys.shape[1]
        att_weights = torch.softmax( att_scores /  d_k **0.5 , dim = -1)
        
        
        context_vector =  att_weights @ values
        
        return context_vector

In [90]:
torch.manual_seed(123)

slef_attention = SelfAttention_V1(3 , 2)

In [91]:
slef_attention.forward(inputs)

tensor([[-0.5337, -0.1051],
        [-0.5323, -0.1080],
        [-0.5323, -0.1079],
        [-0.5297, -0.1076],
        [-0.5311, -0.1066],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)

# causal Attention mask

In [94]:
ll = torch.nn.Linear( d_in, d_out , bias = False)

query =  ll(inputs)
keys =  ll(inputs)
values =  ll(inputs)

att_scores = (query @ keys.T) 



att_scores

tensor([[0.2390, 0.3760, 0.3753, 0.2002, 0.2574, 0.2207],
        [0.3760, 0.7063, 0.7041, 0.3900, 0.4677, 0.4359],
        [0.3753, 0.7041, 0.7020, 0.3887, 0.4664, 0.4345],
        [0.2002, 0.3900, 0.3887, 0.2168, 0.2566, 0.2429],
        [0.2574, 0.4677, 0.4664, 0.2566, 0.3115, 0.2862],
        [0.2207, 0.4359, 0.4345, 0.2429, 0.2862, 0.2724]],
       grad_fn=<MmBackward0>)

In [126]:
con_len =  att_scores.shape[0]

mask_simple =  torch.triu(torch.ones(con_len , con_len) , diagonal = 1)


In [127]:
mask_simple.bool()

tensor([[False,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]])

In [129]:
att_scores = att_scores.masked_fill(mask_simple.bool() ,  -torch.inf)

In [131]:
d_k = keys.shape[1]
att_weights = torch.softmax( att_scores /  d_k **0.5 , dim = -1)
att_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4419, 0.5581, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2840, 0.3583, 0.3578, 0.0000, 0.0000, 0.0000],
        [0.2327, 0.2661, 0.2658, 0.2354, 0.0000, 0.0000],
        [0.1866, 0.2166, 0.2164, 0.1865, 0.1939, 0.0000],
        [0.1556, 0.1811, 0.1810, 0.1580, 0.1629, 0.1614]],
       grad_fn=<SoftmaxBackward0>)

# drop put mask

In [132]:

layer = torch.nn.Dropout(0.5)

# clusal self_attention

In [138]:
batch =  torch.stack( (inputs , inputs) , dim=0 )

batch.shape

torch.Size([2, 6, 3])

In [139]:
class CausalAttention(nn.Module):

    def __init__(self, d_in, d_out, context_length,
                 dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape # New batch dimension b
        # For inputs where `num_tokens` exceeds `context_length`, this will result in errors
        # in the mask creation further below.
        # In practice, this is not a problem since the LLM (chapters 4-7) ensures that inputs  
        # do not exceed `context_length` before reaching this forward method. 
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)  # `:num_tokens` to account for cases where the number of tokens in the batch is smaller than the supported context_size
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights) # New

        context_vec = attn_weights @ values
        return context_vec



In [140]:
torch.manual_seed(123)

context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.0)

context_vecs = ca(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]],

        [[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]]], grad_fn=<UnsafeViewBackward0>)
context_vecs.shape: torch.Size([2, 6, 2])


# Multi head attention 

In [141]:
class MultiHeadAttentionWrapper(nn.Module):

    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList(
            [CausalAttention(d_in, d_out, context_length, dropout, qkv_bias) 
             for _ in range(num_heads)]
        )

    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)




In [142]:
torch.manual_seed(123)

context_length = batch.shape[1] # This is the number of tokens
d_in, d_out = 3, 2
mha = MultiHeadAttentionWrapper(
    d_in, d_out, context_length, 0.0, num_heads=2
)

context_vecs = mha(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]],

        [[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]]], grad_fn=<CatBackward0>)
context_vecs.shape: torch.Size([2, 6, 4])


In [145]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert (d_out % num_heads == 0), \
            "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads # Reduce the projection dim to match desired output dim

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)  # Linear layer to combine head outputs
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length),
                       diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        # As in `CausalAttention`, for inputs where `num_tokens` exceeds `context_length`, 
        # this will result in errors in the mask creation further below. 
        # In practice, this is not a problem since the LLM (chapters 4-7) ensures that inputs  
        # do not exceed `context_length` before reaching this forwar

        keys = self.W_key(x) # Shape: (b, num_tokens, d_out)
        queries = self.W_query(x)
        values = self.W_value(x)

        # We implicitly split the matrix by adding a `num_heads` dimension
        # Unroll last dim: (b, num_tokens, d_out) -> (b, num_tokens, num_heads, head_dim)
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim) 
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)

        # Transpose: (b, num_tokens, num_heads, head_dim) -> (b, num_heads, num_tokens, head_dim)
        keys = keys.transpose(1, 2)
        queries = queries.transpose(1, 2)
        values = values.transpose(1, 2)

        # Compute scaled dot-product attention (aka self-attention) with a causal mask
        attn_scores = queries @ keys.transpose(2, 3)  # Dot product for each head

        # Original mask truncated to the number of tokens and converted to boolean
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]

        # Use the mask to fill attention scores
        attn_scores.masked_fill_(mask_bool, -torch.inf)
        
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        # Shape: (b, num_tokens, num_heads, head_dim)
        context_vec = (attn_weights @ values).transpose(1, 2) 
        
        # Combine heads, where self.d_out = self.num_heads * self.head_dim
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        context_vec = self.out_proj(context_vec) # optional projection

        return context_vec

torch.manual_seed(123)

batch_size, context_length, d_in = batch.shape
d_out = 2
mha = MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)

context_vecs = mha(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]],

        [[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]]], grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 6, 2])


In [146]:
class MHAPyTorchScaledDotProduct(nn.Module):
    def __init__(self, d_in, d_out, num_heads, context_length, dropout=0.0, qkv_bias=False):
        super().__init__()

        assert d_out % num_heads == 0, "d_out is indivisible by num_heads"

        self.num_heads = num_heads
        self.context_length = context_length
        self.head_dim = d_out // num_heads
        self.d_out = d_out

        self.qkv = nn.Linear(d_in, 3 * d_out, bias=qkv_bias)
        self.proj = nn.Linear(d_out, d_out)
        self.dropout = dropout

    def forward(self, x):
        batch_size, num_tokens, embed_dim = x.shape

        # (b, num_tokens, embed_dim) --> (b, num_tokens, 3 * embed_dim)
        qkv = self.qkv(x)

        # (b, num_tokens, 3 * embed_dim) --> (b, num_tokens, 3, num_heads, head_dim)
        qkv = qkv.view(batch_size, num_tokens, 3, self.num_heads, self.head_dim)

        # (b, num_tokens, 3, num_heads, head_dim) --> (3, b, num_heads, num_tokens, head_dim)
        qkv = qkv.permute(2, 0, 3, 1, 4)

        # (3, b, num_heads, num_tokens, head_dim) -> 3 times (b, num_heads, num_tokens, head_dim)
        queries, keys, values = qkv

        use_dropout = 0. if not self.training else self.dropout

        context_vec = nn.functional.scaled_dot_product_attention(
            queries, keys, values, attn_mask=None, dropout_p=use_dropout, is_causal=True)

        # Combine heads, where self.d_out = self.num_heads * self.head_dim
        context_vec = context_vec.transpose(1, 2).contiguous().view(batch_size, num_tokens, self.d_out)

        context_vec = self.proj(context_vec)

        return context_vec


In [150]:
mha_pytorch_scaled = MHAPyTorchScaledDotProduct(
    d_in=3,
    d_out=4,
    context_length=6,
    dropout=0.0,
    num_heads=4,
    qkv_bias=False
)

out = mha_pytorch_scaled(inputs)
print(out.shape)

ValueError: not enough values to unpack (expected 3, got 2)