In [1]:
5+5

10

In [4]:
import torch
import torch.nn as nn 

In [51]:
torch.manual_seed(123)

batch_ecample = torch.randn(2 , 5)
batch_ecample

layer = nn.Sequential( nn.Linear(5 , 6) , nn.ReLU())

In [52]:
out = layer(batch_ecample)
out

tensor([[0.2260, 0.3470, 0.0000, 0.2216, 0.0000, 0.0000],
        [0.2133, 0.2394, 0.0000, 0.5198, 0.3297, 0.0000]],
       grad_fn=<ReluBackward0>)

In [54]:
mean = out.mean(dim = -1 , keepdim=True) 
var  = out.var(dim = -1 , keepdim=True)

In [56]:
(out - mean).mean(dim = -1 , keepdim=True) 

tensor([[-2.4835e-09],
        [ 0.0000e+00]], grad_fn=<MeanBackward1>)

In [58]:
class LayerNorm(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.eps = 1e-5
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))

    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = x.var(dim=-1, keepdim=True, unbiased=False)
        norm_x = (x - mean) / torch.sqrt(var + self.eps)
        return self.scale * norm_x + self.shift

In [59]:
ln = LayerNorm(6)

In [60]:
output_norm = ln(out)
output_norm

tensor([[ 0.6745,  1.5470, -0.9549,  0.6431, -0.9549, -0.9549],
        [-0.0207,  0.1228, -1.1913,  1.6619,  0.6186, -1.1913]],
       grad_fn=<AddBackward0>)